sudo: false
language: elixir
otp_release:
  - 19.3.6.1
elixir:
  - 1.5.1
install:
  - mix local.hex --force
  - mix local.rebar --force
script:
  - mix deps.get
  - mix compile
  - mix test --trace
after_script:
  - mix dialyzer
